version: '3.8'

services:
  visitor-manager:
    image: ghcr.io/bjm021/unifivisitormanager:latest
    container_name: unifi-visitor-manager
    ports:
      - "8080:8080"
    environment:
      - UVM_DATA_DIR=/app/data
    volumes:
      - ./database:/app/data
    restart: unless-stopped