package net.bjmsw.uvm.util;

import de.brendamour.jpasskit.PKBarcode;
import de.brendamour.jpasskit.PKField;
import de.brendamour.jpasskit.PKPass;
import de.brendamour.jpasskit.enums.PKBarcodeFormat;
import de.brendamour.jpasskit.enums.PKPassType;
import de.brendamour.jpasskit.passes.PKGenericPass;
import de.brendamour.jpasskit.signing.PKInMemorySigningUtil;
import de.brendamour.jpasskit.signing.PKPassTemplateInMemory;
import de.brendamour.jpasskit.signing.PKSigningInformation;
import de.brendamour.jpasskit.signing.PKSigningInformationUtil;

import net.bjmsw.uvm.VisitorManager;
import net.bjmsw.uvm.model.Visitor;

import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;

public class PKPassUtil {

    /**
     * Builds the raw PKPass data object containing the visitor's details and the UniFi QR code.
     */
    public static PKPass buildWalletPass(Visitor visitor, String qrData, String eventName) {

        String teamId = VisitorManager.getSettings().getOrDefault("appleTeamId", "TEAM_ID_MISSING");
        String passTypeId = VisitorManager.getSettings().getOrDefault("applePassTypeId", "pass.com.missing");
        String orgName = VisitorManager.getSettings().getOrDefault("appleOrgName", "Meyer&Meyer");

        DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("MMM dd, HH:mm")
                .withZone(ZoneId.systemDefault());
        String formattedStartTime = timeFormatter.format(Instant.ofEpochSecond(visitor.getStart_time()));
        String formattedEndTime = timeFormatter.format(Instant.ofEpochSecond(visitor.getEnd_time()));

        return PKPass.builder()
                .pass(
                        PKGenericPass.builder()
                                .passType(PKPassType.PKGenericPass)
                                // MAIN TEXT: The Visitor's Name right in the middle
                                .primaryFieldBuilder(
                                        PKField.builder()
                                                .key("visitorName")
                                                .value(visitor.getFirstName() + " " + visitor.getLastName())
                                )
                                // SECONDARY TEXT: What the event is
                                .secondaryFieldBuilder(
                                        PKField.builder()
                                                .key("validFrom")
                                                .label("VALID FROM")
                                                .value(formattedStartTime)
                                )
                                .secondaryFieldBuilder(
                                        PKField.builder()
                                                .key("expires")
                                                .label("VALID UNTIL")
                                                .value(formattedEndTime)
                                )
                                .auxiliaryFieldBuilder(
                                        PKField.builder()
                                                .key("event")
                                                .label("EVENT")
                                                .value(eventName != null && !eventName.isBlank() ? eventName : "Building Access")
                                )
                                .auxiliaryFieldBuilder(
                                        PKField.builder()
                                                .key("guest")
                                                .label("GUEST")
                                                .value(visitor.getFirstName() + " " + visitor.getLastName())
                                )
                                .backFieldBuilder(
                                        PKField.builder()
                                                .key("information")
                                                .label("Visitor Information")
                                                .value("This pass allows access to the specified UniFi Access managed location during the valid time period. Please present this pass at the entrance. For any issues, contact the administrator.")
                                )
                                .backFieldBuilder(
                                        PKField.builder()
                                                .key("legal")
                                                .label("Legal Disclaimer")
                                                .value("This pass was generated by UniFi Visitor Manager. For support, contact the administrator.\n\nUniFi Visitor Manager is an open-source project and can be found on GitHub: https://github.com/bjmsw/UniFi-Visitor-Manager\n\nThis is not an official UniFi product and is not affiliated with Ubiquiti Inc. in any way.\n\"Ubiquiti\", \"UniFi\", \"UniFi Access\" and the UniFi logo are registered trademarks of Ubiquiti Inc.")
                                                )
                )
                // INJECT THE EXTRACTED UNIFI TOKEN HERE
                .barcodeBuilder(
                        PKBarcode.builder()
                                .format(PKBarcodeFormat.PKBarcodeFormatQR)
                                .message(qrData)
                                .messageEncoding(StandardCharsets.UTF_8)
                )
                // METADATA & SETTINGS
                .formatVersion(1)
                .passTypeIdentifier(passTypeId)
                .serialNumber(visitor.getId()) // UniFi UUID prevents duplicate passes
                .teamIdentifier(teamId)
                .organizationName(orgName)
                .logoText(orgName) // Text displayed next to the logo icon
                .description("Visitor Access Pass")

                // STYLING: Corporate Blue Theme (Tailwind blue-900)
                .backgroundColor("rgb(30, 58, 138)")
                .foregroundColor("rgb(255, 255, 255)") // White text
                .labelColor("rgb(147, 197, 253)") // Light blue for the "GUEST" and "EVENT" labels
                .build();
    }

    /**
     * Packages the PKPass data, the visual resources, and the Apple certificates into a signed .pkpass byte array.
     */
    public static byte[] signAndZipPass(PKPass pass) throws Exception {

        // 1. Load Certificate Paths from MapDB Settings
        String p12Path = (String) VisitorManager.getSettings().get("appleP12Path");
        String p12Password = (String) VisitorManager.getSettings().get("appleP12Password");
        String wwdrPath = (String) VisitorManager.getSettings().get("appleWwdrPath");

        if (p12Path == null || p12Password == null || wwdrPath == null) {
            throw new IllegalStateException("Apple Wallet certificates are missing from settings!");
        }

        // 2. Load the Cryptographic Signing Information
        PKSigningInformation pkSigningInformation = new PKSigningInformationUtil()
                .loadSigningInformationFromPKCS12AndIntermediateCertificate(
                        p12Path,
                        p12Password,
                        wwdrPath
                );

        // 3. Build the In-Memory Template (Loads from src/main/resources/pass/)
        PKPassTemplateInMemory template = new PKPassTemplateInMemory();

        // Apple Wallet REQUIRES at least an icon.png to be valid.
        addResourceToTemplate(template, "icon.png", "/pass/icon.png");
        addResourceToTemplate(template, "icon@2x.png", "/pass/icon@2x.png");
        addResourceToTemplate(template, "logo.png", "/pass/logo.png");
        addResourceToTemplate(template, "logo@2x.png", "/pass/logo@2x.png");

        // 4. Cryptographically Sign and ZIP the archive using the In-Memory utility
        PKInMemorySigningUtil pkSigningUtil = new PKInMemorySigningUtil();
        return pkSigningUtil.createSignedAndZippedPkPassArchive(pass, template, pkSigningInformation);
    }

    /**
     * Safely streams files from the resources/ folder directly into the memory template.
     */
    private static void addResourceToTemplate(PKPassTemplateInMemory template, String passKitFilename, String resourcePath) throws Exception {
        InputStream is = PKPassUtil.class.getResourceAsStream(resourcePath);
        if (is != null) {
            template.addFile(passKitFilename, is);
        } else {
            System.err.println("[WalletService] Warning: Could not find image resource: " + resourcePath);
        }
    }
}